# Generated by Django 3.2.15 on 2022-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_starred_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_valid',
            field=models.BooleanField(default=False),
        ),
    ]
