# Generated by Django 3.2.15 on 2022-11-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_phone_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='starred_products',
            new_name='favorite_products',
        ),
    ]
