version: '3.10'

services:
  web:
    build: .
    command: gunicorn mystore.wsgi
    expose:
      - ${GUNICORN_PORT}
    volumes:
      - .:/code
    restart: always
#    ports:
#      - ${GUNICORN_PORT}:${GUNICORN_PORT}
    depends_on:
      - db
      - celery
      - celery_beat
      - memcached
    env_file:
      - .env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
  redis:
    image: redis:latest
    restart: always
  celery:
    build: .
    command: celery -A mystore worker -l info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  celery_beat:
    build: .
    command: celery -A mystore beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  memcached:
    image: memcached:latest
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env

volumes:
  postgres_data: