# Generated by Django 3.2.15 on 2022-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyhistory',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(840, 'USD'), (978, 'EUR'), (980, 'UAH')]),
        ),
        migrations.AlterField(
            model_name='currencyhistory',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
