# Generated by Django 3.2.15 on 2022-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(840, 'USD'), (978, 'EUR'), (980, 'UAH')], default=980),
        ),
    ]
