# Generated by Django 3.2.15 on 2022-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
